### ISSUE TITLE
首次登录的时候油箱没有正确设置问题

### ISSUE THREAD

**Issue by yu66433** [zhoujunhe/zentao_dingtalk#1]
用钉钉获取用户信息中，email为空，但"orgEmail"，能不能增加对 orgEmail 的支持？

**Comment by aizhou01** [comment]
查看钉钉文档，orgEmail字段如果员工的企业邮箱没有开通，返回信息中不包含该数据。这样程序会报错，但email是直接返回为"email":""  所以请根据你自己需要，自行把/module/dingtalk/control.php 第52,80行改成如下代码。

`'email'=>$companyuserinfo['email'], ` 改成 ` 'email'=>$companyuserinfo['orgEmail'],`
