### ISSUE TITLE
关于对你代码引用的请求

### ISSUE THREAD

**Issue by yu66433** [zhoujunhe/zentao_dingtalk#2]
一、我根据你代码写了一个支持CAS登录的插件，挂在禅道插件的首页。因为有部分代码是直接贴你的，希望你见谅，如果你不允许的话，我会修改一下。

二、我根据你的代码，我简单整理了一下，可以直接做成禅道的插件，不知道我可不可以直接挂到禅道插件页里？或者我把调整后发给你，由你挂到禅道插件页里？

**Comment by aizhou01** [comment]
当时我想做成禅道插件形式的，后面和官方联系了一下，能不能提供加密等技术支持，他们说不提供，后面我就没有把改成插件化了。你认为可以做成插件化，你就做成插件化吧，让大家都受益。
